# Generated by Django 5.2.5 on 2025-08-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('grado_actual', models.CharField(max_length=200)),
                ('grado_presenta', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
